version: '3'
services:
  openvpn-proxyd:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "1022:22"
      - "3128:3128"
    # Setting the DNS is important
    dns:
      - "${DNS_SERVER_1:-1.1.1.1}"
      - "${DNS_SERVER_2:-8.8.8.8}"
    volumes:
      - ./tmp/config:/config
    environment:
      OPENVPN_PROVIDER: "${OPENVPN_PROVIDER}"
      OPENVPN_USERNAME: "${OPENVPN_USERNAME}"
      OPENVPN_PASSWORD: "${OPENVPN_PASSWORD}"
      # TorGuard already sets a 'keepalive' which is an alias for ping + ping-restart
      # OPENVPN_OPTS: "--inactive 3600 --ping 10 --ping-exit 60"
      OPENVPN_CONFIG: "${OPENVPN_CONFIG}"
      LOCAL_NETWORK: 10.0.0.0/24
