version: '3'

services:

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    depends_on:
      - openvpn-proxyd
    ports:
      - "${PROXY_PORT:-5000}:5000"
    healthcheck:
      test: "healthcheck ${PROXY_PORT:-5000} ${TEST_URL:-https://ipinfo.io/ip}"
      interval: 60s
      retries: 4

  openvpn-proxyd:
    build:
      context: .
      dockerfile: openvpn.dockerfile
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    expose:
      - 3128
    dns:
      - "${DNS_SERVER_1:-1.1.1.1}"
      - "${DNS_SERVER_2:-8.8.8.8}"
    environment:
      OPENVPN_OPTS: "--inactive 3600 --verb 4"
      OPENVPN_PROVIDER: "${OPENVPN_PROVIDER}"
      OPENVPN_USERNAME: "${OPENVPN_USERNAME}"
      OPENVPN_PASSWORD: "${OPENVPN_PASSWORD}"
      OPENVPN_CONFIG: "${OPENVPN_CONFIG}"
      LOCAL_NETWORK: 10.0.0.0/24